service: "sls-template"

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: sa-east-1

functions:
  hello:
    handler: src/handlers/http/hello.handler
    events:
      - http:
          method: GET
          path: hello
          cors: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node16
    define:
      require.resolver: undefined
    platform: node
    concurrency: 10
